version: 2
jobs:
  build:
    docker: 
      - image: gradle:5.4.1-jdk8 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: ls # run the `echo` command
